live_config_reload = true

[keyboard]
bindings = [
	{ key = "D", mods = "Control", chars = "\u0002\u0025" }, # otherwise ctrl+D closes tmux
	{ key = "D", mods = "Control|Shift", chars = "\u0002\u0025" },
	{ key = "T", mods = "Control|Shift", chars = "\u0002c" },
	{ key = "W", mods = "Control|Shift", chars = "\u0002x" }
]

[hints]
[[hints.enabled]]
regex = "(mailto:|https:|http:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\" {-}\\^⟨⟩`]+"
command = "open"
post_processing = true
mouse = { mods = "Command", enabled = true }

[window]
opacity = 0.95
padding = { x = 0, y = 1 }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 13.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = '0xdbdbdb'
background = '0x14191e'

[colors.cursor]
text = '0x000000'
cursor = '0xfefffe'

[colors.selection]
text = '0x000000'
background = '0xb3d7ff'

[colors.bright]
black =   '0x676767'
red =     '0xdc7974'
green =   '0x57e690'
yellow =  '0xece100'
blue =    '0xa6aaf1'
magenta = '0xe07de0'
cyan =    '0x5ffdff'
white =   '0xfeffff'

# normal:
#black:   '0x14191e'
#red:     '0xb43c29'
#green:   '0x00c200'
#yellow:  '0xc7c400'
#blue:    '0x2743c7'
#magenta: '0xbf3fbd'
#cyan:    '0x00c5c7'
#white:   '0xc7c7c7'
